application: openlabs-rietveld
runtime: python27
api_version: 1
threadsafe: false

includes:
- mapreduce/include.yaml

default_expiration: 7d  # This is good for images, which never change

handlers:

- url: /(robots.txt|favicon.ico)
  static_files: static/\1
  upload: static/(robots.txt|favicon.ico)
  secure: optional

- url: /google7db36eb2cc527940.html
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: optional

- url: /static/upload.py
  script: main.application
  secure: optional

# These are fetched with the rietveld version number in the URL.
- url: /static/(script.js|styles.css)
  static_files: static/\1
  upload: static/(script.js|styles.css)
  secure: optional

- url: /static
  static_dir: static
  secure: optional

# Admin-only URLs like tasks or cron jobs. See cron.yaml and queue.yaml.
- url: /restricted/.*
  script: main.application
  login: admin
  secure: optional

# These seem to be hit over http and cannot deal with a 302 to https.
- url: /_ah/(start|stop)
  script: backends.app
  login: admin
  secure: optional

- url: /.*
  script: main.application
  secure: optional

admin_console:
  pages:
  - name: Client ID and Secret Settings
    url: /restricted/set-client-id-and-secret

inbound_services:
- mail
- xmpp_message
- warmup

libraries:
- name: django
  version: 1.4
- name: webapp2
  version: 2.5.2

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
